using CraftForge.Server.Classes.Logs;
using CraftForge.Server.GUI.Console;
using System.IO;

namespace CraftForge.Server.StartPage.Classes
{
    internal class startBatFile
    {
        public static void createNewFile(string fileLocation, int ram, string jarName)
        {
            if (File.Exists(fileLocation))
            {
                File.Delete(fileLocation);
            }
            File.WriteAllText($"{fileLocation}\\start.bat", "::Please do not edit this file! Use the app or it may break the server. You have been warned!"
                + "\n" + "::Displays Java Version for debugging inside console"
                + "\n" + "java -version"
                + "\n" + "::Starts server"
                + "\n" + $"java -Xmx{ram}M -Xms1024M -jar {jarName}.jar nogui");
        }

        public static void resetFile(Terminal terminal, string fileLocation, int ram, string jarName)
        {
            if (File.Exists(fileLocation))
            {
                File.Delete(fileLocation);
            }
            File.WriteAllText($"{fileLocation}\\start.bat", "::This has been Reset Due to Broken File!"
                + "\n" + "::Please do not edit this file! Use the app or it may break the server. You have been warned!"
                + "\n" + "::Displays Java Version for debugging inside console"
                + "\n" + "java -version"
                + "\n" + "::Starts server"
                + "\n" + $"java -Xmx{ram}M -Xms1024M -jar {jarName}.jar nogui");

            createNewLog.sendMessage(terminal, $"[Settings] Reset Start.bat");
        }
    }
}